application: andy-throgmorton
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
# The root URL (/) is handled by the webapp handler in the home.py script.
# No other URLs match this pattern.
- url: /
  script: main.app
  secure: always

# Load any other resource with a given file extension.
- url: /(.*\.(png|jpg|ico|css|less|js|woff|eot|svg|ttf))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|css|less|js|woff|eot|svg|ttf))
  secure: always

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

# Catch all other invalid URLs, direct to 404 page.
- url: /.*
  script: not_found.app
  secure: always
